language: python
matrix:
  fast_finish: true
  include:
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=py38
    - python: '3.8'
      env: TOXENV=cov
    - python: '3.8'
      env: TOXENV=lint
    - python: '3.8'
      env: TOXENV=pylint
    - python: '3.8'
      env: TOXENV=typing
install: pip install -U tox-travis coveralls
script: tox
cache: pip
