language: python
matrix:
  fast_finish: true
  include:
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: '3.8'
      env: TOXENV=lint
install: pip install -U tox-travis coveralls
script: tox
cache: pip
